// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addCareer": {
            "post": {
                "description": "Add player career",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "parameters": [
                    {
                        "description": "Adds Player career",
                        "name": "playerCareer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Career"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/addPlayertoTeam": {
            "post": {
                "description": "Add player to team",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the team",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Array of players",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/addToScoreCard": {
            "post": {
                "description": "stores players info in scorecard",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Scorecard"
                ],
                "parameters": [
                    {
                        "description": "ScoreCard details",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CardData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/adminRegister": {
            "post": {
                "description": "Registers a admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "Registers a admin",
                        "name": "UserDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Credential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/ballUpdate": {
            "put": {
                "description": "Update the ball",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ball"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id of the ball",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/createMatch": {
            "post": {
                "description": "Create the match between the teams",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "parameters": [
                    {
                        "description": "Match details",
                        "name": "match",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Match"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/createPlayer": {
            "post": {
                "description": "Creates a new Player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "parameters": [
                    {
                        "description": "Create Player",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Player"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/createTeam": {
            "post": {
                "description": "Creates a team",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the user",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Details of the team",
                        "name": "TeamDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Team"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/decisionUpdate": {
            "put": {
                "description": "Updates the decison taken by the team after wining the toss",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Toss"
                ],
                "parameters": [
                    {
                        "description": "Descision Updated",
                        "name": "toss",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Toss"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/deleteMatch": {
            "delete": {
                "description": "Deletes the match",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "parameters": [
                    {
                        "description": "Match Id",
                        "name": "matchId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/deleteTeamByID": {
            "delete": {
                "description": "Delete the team",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "parameters": [
                    {
                        "description": "ID of the team",
                        "name": "teamId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"teamId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/endInning": {
            "post": {
                "description": "Ends the current team innings",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Inning"
                ],
                "parameters": [
                    {
                        "description": "Id of the team to end its inning",
                        "name": "matchDetils",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"matchId\":\"string\",\n \"teamId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/endMatch": {
            "post": {
                "description": "Ends the match and updates the scorecard of every player",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "parameters": [
                    {
                        "description": "Id of the match to end it",
                        "name": "matchDetils",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"matchId\":\"string\",\n \"teamId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/logOut": {
            "get": {
                "description": "Logs out a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/retirePlayer": {
            "delete": {
                "description": "Shows the list of all the player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "parameters": [
                    {
                        "description": "ID of the player",
                        "name": "playerId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"playerId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/sendOTP": {
            "post": {
                "description": "Sends a OTp to the nuber entered",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "Phone Number of registered user",
                        "name": "phoneNumber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"phoneNumber\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showMatch": {
            "post": {
                "description": "Show the list of matches",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showMatchById": {
            "post": {
                "description": "Shows a particular match",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "parameters": [
                    {
                        "description": "Id of the match ",
                        "name": "matchDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"matchId\":\"string\" \n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showPlayer": {
            "get": {
                "description": "Shows the list of all the player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/showPlayerID": {
            "get": {
                "description": "Shows the list of all the player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "parameters": [
                    {
                        "description": "ID of the player",
                        "name": "playerId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"playerId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showScoreCard": {
            "post": {
                "description": "Shows the score card for the current matcha",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Scorecard"
                ],
                "parameters": [
                    {
                        "description": "Id of the match whose scorecard is to be shown",
                        "name": "matchId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"matchId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showTeamByID": {
            "post": {
                "description": "Shows the list of teams",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "parameters": [
                    {
                        "description": "ID of the team",
                        "name": "teamId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n \"userId\":\"string\",\n \"teamId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/showTeams": {
            "get": {
                "description": "Shows the list of teams",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "parameters": [
                    {
                        "description": "ID of the User",
                        "name": "userId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"userId\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/tossResult": {
            "post": {
                "description": "Give the random result of coin toss and which team won the toss",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Toss"
                ],
                "parameters": [
                    {
                        "description": "Toss Details",
                        "name": "toss",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Toss"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/updateProfile": {
            "post": {
                "description": "Updates the data of the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "user updated datas",
                        "name": "userDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Credential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/userRegister": {
            "post": {
                "description": "Registers a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "Registers a user",
                        "name": "UserDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Credential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/verifyOTP": {
            "post": {
                "description": "Verifies the OTP sent to the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "parameters": [
                    {
                        "description": "Phone Number of registered user and the otp sent to it",
                        "name": "details",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"phoneNumber\":\"string\",\n\"otp\":\"string\"\n}"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.CardData": {
            "type": "object",
            "required": [
                "ballType",
                "baller",
                "batsmen",
                "matchId",
                "runs"
            ],
            "properties": {
                "ballType": {
                    "type": "string"
                },
                "baller": {
                    "type": "string"
                },
                "batsmen": {
                    "type": "string"
                },
                "matchId": {
                    "type": "string"
                },
                "prevRuns": {
                    "type": "integer"
                },
                "runs": {
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7
                    ]
                }
            }
        },
        "models.Career": {
            "type": "object",
            "properties": {
                "averageScore": {
                    "type": "number"
                },
                "ballsBowled": {
                    "description": "Balls Bowled",
                    "type": "integer"
                },
                "ballsFaced": {
                    "type": "integer"
                },
                "bowlingAverage": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "economy": {
                    "type": "number"
                },
                "fifties": {
                    "type": "integer"
                },
                "fours": {
                    "type": "integer"
                },
                "highestScore": {
                    "description": "high score",
                    "type": "integer"
                },
                "hundreds": {
                    "type": "integer"
                },
                "matchesPlayed": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "string"
                },
                "runScored": {
                    "type": "integer"
                },
                "runsConced": {
                    "description": "Runs Conceded",
                    "type": "integer"
                },
                "sixes": {
                    "type": "integer"
                },
                "twoHundreds": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "wickets": {
                    "type": "integer"
                }
            }
        },
        "models.Credential": {
            "type": "object",
            "required": [
                "phoneNumber",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "isLoggedIn": {
                    "type": "boolean"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Match": {
            "type": "object",
            "required": [
                "team1Id",
                "team2Id",
                "venue"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "matchId": {
                    "type": "string"
                },
                "scorecardId": {
                    "description": "scorecard related to it",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "team1Id": {
                    "type": "string"
                },
                "team2Id": {
                    "type": "string"
                },
                "text": {
                    "description": "who won the match/",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "venue": {
                    "type": "string"
                }
            }
        },
        "models.Player": {
            "type": "object",
            "required": [
                "country",
                "jerseyNo",
                "phoneNo",
                "playerAge",
                "playerName"
            ],
            "properties": {
                "country": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "jerseyNo": {
                    "type": "integer"
                },
                "phoneNo": {
                    "type": "string"
                },
                "playerAge": {
                    "type": "integer"
                },
                "playerId": {
                    "type": "string"
                },
                "playerName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Team": {
            "type": "object",
            "required": [
                "teamCaptain",
                "teamName",
                "teamType"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "playerId": {
                    "type": "string"
                },
                "teamCaptain": {
                    "type": "string"
                },
                "teamId": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                },
                "teamType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.Toss": {
            "type": "object",
            "required": [
                "head_team",
                "match_id",
                "tail_team"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "decision": {
                    "type": "string"
                },
                "head_team": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "tail_team": {
                    "type": "string"
                },
                "toss_id": {
                    "type": "string"
                },
                "toss_won": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Cric Heros API",
	Description:      "API Documentation for Cric Heros",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
